### ISSUE TITLE
Root node in crashing after a deposit

### ISSUE THREAD

**Issue by lgalabru** [kyokan/plasma#52]
After performing a deposit to the plasma contract using
 
    plasma deposit --amount=1000000

The root node crashes (and keep crashing when relaunched). Logs available here:

    2018/06/25 12:00:58 Starting RPC server on port 8643.
    2018/06/25 12:00:58 Looking for deposit events at block number: 0
    2018/06/25 12:00:58 Awaiting transactions.
    2018/06/25 12:00:58 Failed to filter deposit events: json: cannot unmarshal hex number with leading zero digits into Go struct field Log.logIndex of type hexutil.Uint

Simulating main-net with ganache, and running a private chain with Geth as suggested by the documentation.
Any hint?

**Comment by mslipper** [comment]
Weird. I'll look into this.

**Comment by mslipper** [comment]
This should be fixed now.
