### ISSUE TITLE
Import or require [[constraint]] dependencies (uuid & cli)

### ISSUE THREAD

**Issue by TiuTalk** [kyokan/plasma#87]
When running `dep ensure` I received the following warning:

```
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  github.com/pborman/uuid
  ✗  gopkg.in/urfave/cli.v1

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.
```

**Comment by mslipper** [comment]
Which branch are you on?

**Comment by ChrisChinchilla** [comment]
@mslipper I have the same issue on `master` branch.

**Comment by mslipper** [comment]
Cool, thanks. We'll be merging `develop` into `master` by the end of the month after our security audit completes, at which point I'll make sure that this error is removed.

**Comment by ChrisChinchilla** [comment]
OK @mslipper just to clarify. There's the same problem in the master branch, and at the moment, the default branch people see is the `deploy` branch. So currently, it's impossible to install and make Plasma MVP from either branch.
