### ISSUE TITLE
Plasma.sol location

### ISSUE THREAD

**Issue by ChrisChinchilla** [kyokan/plasma#94]
If you follow https://plasma.kyokan.io/docs/installation/ at the "Deploying Plasma.sol" section you are told to deploy the contract but with no details as to where it is if you've just installed from a Binary. Not sure of the best solution to this?

**Comment by mslipper** [comment]
Plasma.sol is deprecated - we're currently targeting having FourthState's contract integrated by January 18th.

**Comment by ChrisChinchilla** [comment]
OK cool @mslipper
