### ISSUE TITLE
Typo in Truffle command

### ISSUE THREAD

**Issue by ChrisChinchilla** [kyokan/plasma#95]
I'd make PRs, but can't see site source anywhere.

In https://plasma.kyokan.io/docs/installation/  the truffle command has a 'f' missing.

Should be.

`$ PRIVATE_KEY='<your private key, in hex>' HOST='<your Ethereum node>' truffle migrate --network <network name>`

**Comment by mslipper** [comment]
The site source uses a paid theme, so we can't open-source the site without permission from the license holder. I'll fix the site - will close this issue when that's done.

**Comment by mslipper** [comment]
This is fixed now.
