### ISSUE TITLE
Load Testing Results: "invalid transaction rejected from mempool"

### ISSUE THREAD

**Issue by kirushanths** [kyokan/plasma#98]
Running MacBook Pro (15-inch, 2017) on MacOS Mojave 10.13.

I have the latest master as of 714937a10b4093addf8475439059bd8761fe7553.
I have `plasmad` running alongside `plasma-harness`.

Regular one-off singular transactions such as `deposit` and `send` are fine and run smoothly.
However, I want to see the performance of the system, so using GNU `parallel`.
GNU Parallel installed via brew `brew install parallel`

I'm hammering this command 1000x times:
`./target/plasmacli send 0x821aea9a577a9b44299b9c15c88cf3087f3b5544 1`

The final `parallel` command looks like this:
`parallel --joblog ./results.log -N0 ./target/plasmacli send 0x821aea9a577a9b44299b9c15c88cf3087f3b5544 1 ::: {1..1000}`

I am seeing about roughly 1000 transactions completed per **minute**.
However, about 10-20% of them error out with the following (from `plasmad` logs):
```
WARN[1359] invalid transaction rejected from mempool     hash=0x68afb9e4ccd82f454fadd969e83b45ca77e40910e149eb7c26e5921eba780cf3 reason="<nil>" subsystem=Mempool
```

The actual `plasmacli send` command returns this (which isn't really useful or revealing):
```
time="2019-02-07T14:51:54-05:00" level=info msg="selecting outputs" subsystem=SendCmd
time="2019-02-07T14:51:54-05:00" level=info msg="sending transaction" subsystem=SendCmd
time="2019-02-07T14:51:54-05:00" level=info msg="confirming transaction" subsystem=SendCmd
Error: rpc error: code = Unknown desc = leveldb: not found
Usage:
  plasmacli send to value [flags]

Flags:
  -h, --help   help for send

Global Flags:
  -u, --node-url string           URL to a running plasmad instance. (default "localhost:6545")
  -p, --private-key-path string   Path to your private key. (default "~/.plasma/key")

rpc error: code = Unknown desc = leveldb: not found
```

I'm continuing to debug myself but any guidance would be helpful.
fyi @mslipper

**Comment by mslipper** [comment]
Thanks @kirushanths! This is really helpful. What I think is happening here is that your account doesn't have enough UTXOs to fund transactions at that rate, so the mempool is rejecting them.

Can you run `plasmacli utxos <address>` and tell me how many outputs there are? The maximum parallelism you can achieve _per block_ is bounded by the number of outputs you have available to your account. To make more outputs, you can basically send yourself money until you have enough. Alternatively, you can structure your performance testing to use different accounts for each test run.

**Comment by mslipper** [comment]
This is resolved.
